# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab07_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.c = QtWidgets.QGraphicsView(self.centralwidget)
        self.c.setGeometry(QtCore.QRect(15, 11, 721, 781))
        self.c.setObjectName("c")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(750, 10, 351, 441))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 321, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.x1_entry = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.x1_entry.setObjectName("x1_entry")
        self.gridLayout.addWidget(self.x1_entry, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.y1_entry = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.y1_entry.setObjectName("y1_entry")
        self.gridLayout.addWidget(self.y1_entry, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        self.x2_entry = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.x2_entry.setObjectName("x2_entry")
        self.gridLayout.addWidget(self.x2_entry, 0, 4, 1, 1)
        self.y2_entry = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.y2_entry.setObjectName("y2_entry")
        self.gridLayout.addWidget(self.y2_entry, 1, 4, 1, 1)
        self.add_point = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.add_point.setObjectName("add_point")
        self.gridLayout.addWidget(self.add_point, 2, 0, 1, 5)
        self.point_num_entry = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.point_num_entry.setObjectName("point_num_entry")
        self.gridLayout.addWidget(self.point_num_entry, 3, 4, 1, 1)
        self.delete_point = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delete_point.setObjectName("delete_point")
        self.gridLayout.addWidget(self.delete_point, 3, 0, 1, 3)
        self.clear_all = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clear_all.setObjectName("clear_all")
        self.gridLayout.addWidget(self.clear_all, 6, 0, 1, 5)
        self.list_point = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.list_point.setObjectName("list_point")
        self.gridLayout.addWidget(self.list_point, 7, 0, 1, 5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(750, 450, 351, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 331, 72))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        self.cutter = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cutter.setFont(font)
        self.cutter.setObjectName("cutter")
        self.gridLayout_2.addWidget(self.cutter, 2, 0, 1, 1)
        self.lines_draw = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lines_draw.setFont(font)
        self.lines_draw.setObjectName("lines_draw")
        self.gridLayout_2.addWidget(self.lines_draw, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(760, 550, 341, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 331, 176))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 0, 1, 1)
        self.col_cut_shoose = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.col_cut_shoose.setObjectName("col_cut_shoose")
        self.gridLayout_3.addWidget(self.col_cut_shoose, 3, 2, 1, 1)
        self.c_col_cut = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        self.c_col_cut.setMaximumSize(QtCore.QSize(50, 50))
        self.c_col_cut.setObjectName("c_col_cut")
        self.gridLayout_3.addWidget(self.c_col_cut, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 2)
        self.c_col_line = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        self.c_col_line.setMaximumSize(QtCore.QSize(50, 50))
        self.c_col_line.setObjectName("c_col_line")
        self.gridLayout_3.addWidget(self.c_col_line, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 1, 1, 2)
        self.col_line_choose = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.col_line_choose.setObjectName("col_line_choose")
        self.gridLayout_3.addWidget(self.col_line_choose, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 4, 2, 1, 1)
        self.cut_button = QtWidgets.QPushButton(self.centralwidget)
        self.cut_button.setGeometry(QtCore.QRect(760, 750, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cut_button.setFont(font)
        self.cut_button.setObjectName("cut_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Добавление и редактирование отрезков"))
        self.label_2.setText(_translate("MainWindow", "Координаты Y1 Y2"))
        self.label.setText(_translate("MainWindow", "Координаты Х1 X2"))
        self.add_point.setText(_translate("MainWindow", "Добавить отрезок"))
        self.delete_point.setText(_translate("MainWindow", "Удалить отрезок номер"))
        self.clear_all.setText(_translate("MainWindow", "Очистить все поля"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Режим"))
        self.cutter.setText(_translate("MainWindow", "Отсечение"))
        self.lines_draw.setText(_translate("MainWindow", "Построение отрезков"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Выбор цвета"))
        self.col_cut_shoose.setText(_translate("MainWindow", "Выбрать цвет"))
        self.label_4.setText(_translate("MainWindow", "                    Цвет отрезков"))
        self.label_6.setText(_translate("MainWindow", "                    Цвет отсекателя"))
        self.col_line_choose.setText(_translate("MainWindow", "Выбрать цвет"))
        self.cut_button.setText(_translate("MainWindow", "Отсечь"))


